name: Java CI/CD

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'


  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Linter
        run: mvn checkstyle:check


  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Run Unit Tests
        run: mvn test


  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Package Artifact
        run: mvn package


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

