name: CI Dispatcher

on:
  push:
    paths:
      - 'orders-service/**'
      - 'products-service/**'
      - 'recommendations-service/**'

jobs:
  java-ci:
    if: contains(github.event.head_commit.message, 'orders-service') || github.event_name == 'push' && github.event.commits.*.modified.* contains 'orders-service/'
    uses: ./.github/workflows/java-ci.yaml

  node-ci:
    if: contains(github.event.head_commit.message, 'products-service') || github.event_name == 'push' && github.event.commits.*.modified.* contains 'products-service/'
    uses: ./.github/workflows/node-ci.yaml

  python-ci:
    if: contains(github.event.head_commit.message, 'recommendations-service') || github.event_name == 'push' && github.event.commits.*.modified.* contains 'recommendations-service/'
    uses: ./.github/workflows/python-ci.yaml
