name: CI/CD Dispatcher

on:
  push:
    paths:
      - '**/project-blueprint.yaml'
      - '**/*.java'
      - '**/*.py'
      - '**/*.js'
      - '.github/workflows/**'
  workflow_dispatch: # Allow manual trigger

jobs:
  read-blueprint:
    runs-on: ubuntu-latest
    outputs:
      language: ${{ steps.extract.outputs.language }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install yq and extract blueprint info
        id: extract
        run: |
          YQ_VERSION="v4.40.5"
          sudo wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          
          FILE=$(find . -type f -name project-blueprint.yaml | head -n 1)
          echo "Found blueprint: $FILE"
          echo "blueprint_path=$FILE" >> $GITHUB_OUTPUT

          LANG=$(yq e '.language' "$FILE")
          echo "language=$LANG"
          echo "language=$LANG" >> $GITHUB_OUTPUT

  java-ci:
    needs: read-blueprint
    if: ${{ needs.read-blueprint.outputs.language == 'java' }}
    uses: ./.github/workflows/java-ci.yml

  python-ci:
    needs: read-blueprint
    if: ${{ needs.read-blueprint.outputs.language == 'python' }}
    uses: ./.github/workflows/python-ci.yml

  node-ci:
    needs: read-blueprint
    if: ${{ needs.read-blueprint.outputs.language == 'node' }}
    uses: ./.github/workflows/node-ci.yml
