name: CI Pipeline

on:
  push:

jobs:
  read-blueprint:
    name: read-blueprint
    runs-on: ubuntu-latest
    outputs:
      language: ${{ steps.detect.outputs.language }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect language
        id: detect
        run: |
          if [ -f "./orders-service/pom.xml" ]; then
            echo "language=java" >> $GITHUB_OUTPUT
          elif [ -f "./orders-service/package.json" ]; then
            echo "language=node" >> $GITHUB_OUTPUT
          elif [ -f "./orders-service/main.py" ]; then
            echo "language=python" >> $GITHUB_OUTPUT
          else
            echo "language=unknown" >> $GITHUB_OUTPUT
          fi

  # ====================
  # Java Pipeline
  # ====================
  java-lint:
    name: java-ci / lint
    needs: read-blueprint
    if: ${{ needs.read-blueprint.outputs.language == 'java' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Java
        run: echo "Running Java lint"

  java-test:
    name: java-ci / test
    needs: java-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Java
        run: echo "Running Java tests"

  java-build:
    name: java-ci / build
    needs: java-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Java
        run: |
          cd orders-service
          mvn package

  java-deploy:
    name: java-ci / deploy
    needs: java-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Java
        run: echo "Deploying Java service"

  # ====================
  # Node.js Pipeline
  # ====================
  node-build:
    name: node-ci / node-build
    needs: read-blueprint
    if: ${{ needs.read-blueprint.outputs.language == 'node' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Node install and build
        run: |
          cd orders-service
          npm ci
          npm run build

  # ====================
  # Python Pipeline
  # ====================
  python-build:
    name: python-ci / python-build
    needs: read-blueprint
    if: ${{ needs.read-blueprint.outputs.language == 'python' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python build and check
        run: |
          cd orders-service
          python -m py_compile main.py
