name: CI/CD Dispatcher

on:
  push:
    paths:
      - '**/project-blueprint.yaml'
      - '**/src/**'
      - '**/*.java'
      - '**/*.py'
      - '**/*.js'
  workflow_dispatch:

jobs:
  read-blueprint:
    runs-on: ubuntu-latest
    outputs:
      language: ${{ steps.vars.outputs.language }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          sudo apt-get update && sudo apt-get install -y yq

      - name: Detect service directory
        id: service
        run: |
          service_dir=$(find . -name "project-blueprint.yaml" -exec dirname {} \;)
          echo "service_dir=$service_dir" >> $GITHUB_OUTPUT

      - name: Read blueprint config
        id: vars
        run: |
          cd ${{ steps.service.outputs.service_dir }}
          echo "language=$(yq e '.language' project-blueprint.yaml)" >> $GITHUB_OUTPUT

  dispatch:
    needs: read-blueprint
    uses: ./.github/workflows/${{ needs.read-blueprint.outputs.language }}-ci.yml
