# .github/workflows/node-ci.yml
name: Node CI

on:
  workflow_call:
    inputs:
      blueprint:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ESLint
        run: echo "Run ESLint here"

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: echo "Run Node.js tests here"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Build Node App
        run: echo "Build Node.js app"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Node App
        run: echo "Deploy Node.js app"
